palavras = "banana", "melancia", "morango", "cachorro", "porteira", "hotel", "chuveiro", "python", "cascavel", "elefante", "geladeira", "aparelho", "papelaria", "Lab",
"Grelha",
"Voto",
"Estacionamento",
"Dinamite",
"Jovem",
"Cura",
"Real",
"Sogra",
"Passagem",
